// Copyright 2019 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_ota_control                     23
#define gattdb_ota_mcu                         25
#define gattdb_bin_1                           28
#define gattdb_bin_2                           31
#define gattdb_bin_3                           34
#define gattdb_bin_4                           37
#define gattdb_bin_5                           40
#define gattdb_bin_6                           42
#define gattdb_bin_7                           44
#define gattdb_bin_8                           46
#define gattdb_bin_9                           48
#define gattdb_bin_10                          50
#define gattdb_bin_11                          52
#define gattdb_bin_12                          54
#define gattdb_bin_13                          56
#define gattdb_bin_14                          58
#define gattdb_bin_15                          60
#define gattdb_bin_16                          62
#define gattdb_bin_17                          64
#define gattdb_bin_18                          66
#define gattdb_bin_19                          68
#define gattdb_bin_20                          70
#define gattdb_hours_pumped                    73
#define gattdb_stroke_count                    76
#define gattdb_raw_value                       79
#define gattdb_scaled_value                    82

#endif
