// Copyright 2019 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_hours_pumped                    23
#define gattdb_stroke_count                    26
#define gattdb_raw_value                       29
#define gattdb_scaled_value                    32
#define gattdb_Strokes                         36
#define gattdb_Run_hours                       39
#define gattdb_PSI                             42
#define gattdb_Bins                            45
#define gattdb_Control_Input                   48
#define gattdb_ota_control                     51
#define gattdb_ota_data                        53
#define gattdb_ota_mcu_control                 55
#define gattdb_ota_mcu_data                    57
#define gattdb_location_and_speed              60

#endif
