// Copyright 2019 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_ota_data                        23
#define gattdb_ota_control                     25
#define gattdb_ota_mcu_control                 27
#define gattdb_ota_mcu_data                    30
#define gattdb_Strokes                         33
#define gattdb_Run_hours                       36
#define gattdb_PSI                             39
#define gattdb_Bins                            42
#define gattdb_Control_Input                   45
#define gattdb_Accelerometer                   47
#define gattdb_location_and_speed              50
#define gattdb_Erase_Firmware                  54
#define gattdb_Flash_Firmware                  56
#define gattdb_Firmware_Data                   58
#define gattdb_Firmware_Control                60

#endif
